name: manex_odoo_repository
description: "Odoo Repository modificado por Manexware para versión 12, 16 y 17."
version: 0.0.2
homepage: 'https://www.manexware.com'
repository: 'https://github.com/mangrovex/manex_odoo_repository'
issue_tracker: 'https://github.com/mangrovex/manex_odoo_repository/issues'

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  odoo_rpc: ^0.6.0
  logger: ^2.5.0
  crypto: ^3.0.6
  lints: ^5.1.1
  mutex: ^3.1.0
  http: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

maintainers:
  - Manuel Vega Ulloa <manuel.vega@manexware.com>
