name: manex_odoo_repository
description: "Odoo Repository modificado por Manexware para versión 12, 16 y 17."
version: 0.0.1
homepage: 'https://www.manexware.com'
repository: 'https://github.com/mangrovex/banner_carousel_odoo'
issue_tracker: 'https://github.com/mangrovex/banner_carousel_odoo/issues'

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  odoo_rpc: ^0.5.4
  logger: ^2.2.0
  crypto: ^3.0.3
  lints: ^3.0.0
  mutex: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

maintainers:
  - Manuel Vega Ulloa <manuel.vega@manexware.com>
